name: Build, Test and Package For Develop Branch

on:
  push:

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install deps
        run: yarn --prefer-offline --frozen-lockfile

      - name: Publish
        run: |
          yarn semrel \
            --deps.bump="override" \
            --deps.release="inherit" \
            --deps.prefix="^" \
            --debug

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}